
server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    # 如果时区报错就加上: serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/awedev?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 整合mybatis
mybatis:
  type-aliases-package: com.awe.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

